name: Build
on:
  push:
    branches:
      - main
    paths: # only trigger build for actual code changes, i.e. readme and other changes don't cause that issues
      - 'src/**'
      - 'tundra.nimble'
      - '.github/workflows/**'

jobs:
  build-win-debug:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Get git short hash
        id: git_short_hash
        run: echo "result=$(git rev-parse --short "${{ github.sha }}")" >> $GITHUB_OUTPUT
        shell: bash
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.2' # ex: 1.0.x, 1.2.x, 1.4.x ...
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Packages
        run: nimble install -Y

      - name: Build for Windows
        run: nake release -d:TUNDRA_COMMIT=${{steps.git_short_hash.outputs.result}}
      
      - name: Build Debug for Windows
        run: nake debug -d:TUNDRA_COMMIT=${{steps.git_short_hash.outputs.result}}
  
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tundra
          path: bin/tundra.exe
      - name: Upload debug build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tundra-debug
          path: "tundra-debug.exe"
  # build-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Get git short hash
  #       id: git_short_hash
  #       run: echo "result=$(git rev-parse --short "${{ github.sha }}")" >> $GITHUB_OUTPUT
  #       shell: bash
  #     - name: Setup nim
  #       uses: jiro4989/setup-nim-action@v1
  #       with:
  #         nim-version: '2.0.0' # ex: 1.0.x, 1.2.x, 1.4.x ...
  #         repo-token: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Install Packages
  #       run: nimble install -Y
  #     - name: Build for Linux
  #       run: nimble build -d:NOBA_COMMIT=${{steps.git_short_hash.outputs.result}}

  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: noba
  #         path: build/noba